version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY-}example
    build:
      context: .
      dockerfile: MagniseTask.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"